version: "3.8"

services:
  proxy: 
    image: nginx:1.20
    volumes: 
      - .docker-config/nginx/conf.d/:/etc/nginx/templates/
    ports:
      - 80:80
      # 443 + ssl

  app:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
  
  redis: # should use alpine images
    image: redis:6.0 # check if python redis==2.10.3 works with specific version
    # specify env with config (pass, ency)
    command: ["redis-server", "--bind", "redis", "--port", "6379"]